---
title: "Electric Vehicles Reach"
subtitle: "How far can I travel in Mexico with my Tesla?"
author: "Edgar Daniel"
page-layout: article
output: html_document
---


# Question: Going from Mexico City, how far can I go in a roadtrip using my Tesla and charging in the official charger network.

In this report we try to identify the towns and cities that are reachable using and electric car based on public data about  batery charging times, time budget constraints, averge distance per kW , and considering the following assumptions:

**Problem Statement**:

Consider the following scenario:  you want to decide where can you go to vacation on your Tesla by charging just in the official carger spots across the countrty and using the available roads. 

> 1.- The start point is in the center of Mexico City with a fully charged car. 
> 
> 2.- For cities and towns where there are a charger/super-charger, it is assumed that we can travel the whole city/town.
> 
> 3.- For the cities and towns whithout charger/super-charger in order to say that is reacheable, the vehicle should have enough battery to get to the nearest point on the town next to the road, and for the return/ travel to the closest charger, remaining at the end a 5%  battery margen. 
> 
> 4.- For the road network we use the official Mexico INEGI's Red Nacional de Caminos (National Road Network). 
> 
> 5.- The carger are obtained from the official Tesla web Sites. 


## Problem definition and theory



### The problem itself 


### The strategy 




 ```{r,echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(readr)
library(maps)
library(leaflet)
library(leaflet.extras)

# Paths 
SAMPLE_DATA <- "../data/sample"

MARCOGEO_FOLDER <- "/marco_geo_2020" 
CENSO_FOLDER <- "/mex_censo_2020" 

CENSO_GEOJSON <-  "/inegi_censo_2020_urbageb.geojson"
CELLS_GEOJSON <-  "/cells_censo_2020_urbageb.geojson"

# Parameters
H3_RESOLUTION <- 8

```


## Data Preparation 



